### ISSUE TITLE
Feature: show countdown if it's not birthday time.

### ISSUE THREAD

**Issue by beatgammit** [booyaa/cargo-cake#1]
I think it makes sense to show the cake for a week following Rust's actual birthday so as to allow people to celebrate a little late. This is a bit more helpful than the current "come back on May 15th" message.

This allows removal of the warning on the README:

> Warning: do not use when not birthday time

**Comment by booyaa** [comment]
done in 2f99aee8d3fbfca7eba237275802d6371c200ac4

thanks for the suggestion!

I've kept the warning, because people loving breaking the rules ;)
